backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images/covers"
site_url: https://highlights.josephmos.es
display_url: https://highlights.josephmos.es
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{book}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Book", name: "book", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "tags" }
  - name: "highlights" # Used in routes, e.g., /admin/collections/blog
    extension: yaml
    label: "Highlights" # Used in the UI
    summary: '{{filename}}'
    folder: "_data/books" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    #slug: "{{filename}}" # Filename template, e.g., YYYY-MM-DD-title.md
    widget: "list"
    fields: # The fields for each document, usually in front matter
      - { label: "Text", name: "text", widget: "string" }
      - { label: "Page", name: "page", widget: "string" }
